# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credited_to',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debited_from',
            field=models.CharField(max_length=20),
        ),
    ]
