# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20170812_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
