# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20170812_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='time',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='username_of_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
