# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20170813_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='debited_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='username_of_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taker', to=settings.AUTH_USER_MODEL),
        ),
    ]
