# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20170814_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='currency',
            field=models.CharField(choices=[('AUD', 'Australian Dollar'), ('THB', 'Baht'), ('BRL', 'Brazilian Real'), ('BGN', 'Bulgarian Lev'), ('CAD', 'Canadian Dollar'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('EUR', 'Euro'), ('HUF', 'Forint'), ('HKD', 'Hong Kong Dollar'), ('INR', 'Indian Rupee'), ('HRK', 'Kuna'), ('MYR', 'Malaysian Ringgit'), ('MXN', 'Mexican Peso'), ('ILS', 'New Israeli Sheqel'), ('NZD', 'New Zealand Dollar'), ('NOK', 'Norwegian Krone'), ('PHP', 'Philippine Peso'), ('GBP', 'Pound Sterling'), ('ZAR', 'Rand'), ('RON', 'Romanian Leu'), ('IDR', 'Rupiah'), ('RUB', 'Russian Ruble'), ('SGD', 'Singapore Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('TRY', 'Turkish Lira'), ('USD', 'US Dollar'), ('KRW', 'Won'), ('JPY', 'Yen'), ('CNY', 'Yuan Renminbi'), ('PLN', 'Zloty')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('AUD', 'Australian Dollar'), ('THB', 'Baht'), ('BRL', 'Brazilian Real'), ('BGN', 'Bulgarian Lev'), ('CAD', 'Canadian Dollar'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('EUR', 'Euro'), ('HUF', 'Forint'), ('HKD', 'Hong Kong Dollar'), ('INR', 'Indian Rupee'), ('HRK', 'Kuna'), ('MYR', 'Malaysian Ringgit'), ('MXN', 'Mexican Peso'), ('ILS', 'New Israeli Sheqel'), ('NZD', 'New Zealand Dollar'), ('NOK', 'Norwegian Krone'), ('PHP', 'Philippine Peso'), ('GBP', 'Pound Sterling'), ('ZAR', 'Rand'), ('RON', 'Romanian Leu'), ('IDR', 'Rupiah'), ('RUB', 'Russian Ruble'), ('SGD', 'Singapore Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('TRY', 'Turkish Lira'), ('USD', 'US Dollar'), ('KRW', 'Won'), ('JPY', 'Yen'), ('CNY', 'Yuan Renminbi'), ('PLN', 'Zloty')], max_length=100),
        ),
    ]
