# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20170826_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='Acc_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
